version: "3.7"
services:
  phplist:
    build: ./phplist
    container_name: phplist
    restart: always
    ports:
      - "1231:80"
    networks:
      - network
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/phplist/config.php:/var/www/html/config/config.php
      - ./config/phplist/config_extended.php:/var/www/html/config/config_extended.php
      - ./.logs/apache:/var/log/httpd
      - ./.logs/php:/var/log/php
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.5.62
    container_name: phplistdb
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123394
      - MYSQL_DATABASE=phplist
    expose:
      - "3306"
    networks:
      - network
    volumes:
      - ./config/mysql/mysql.conf:/etc/mysql/conf.d/my.cnf
      - ./.mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phplist_db_admin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    links:
      - db
    networks:
      - network
networks:
  network:
